quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=Admin
quarkus.datasource.password=admin.1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/empresa_fletes

#quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation=drop-and-create
